version: '3.4'
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
      - '8002:8002'
volumes:
  dbdata:
